# version: "3.9"

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./Backend
    network_mode: host
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=sig1234
      - DB_NAME=SIG
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sig1234
      MYSQL_DATABASE: SIG
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
